- src/Container.php
> Fix: Add missing leading slash

- .travis.yml
> Enhancement: Allow to finish the build fast

- .travis.yml
> Fix: Move build steps to appropriate sections

- src/Definition/DefinitionFactory.php
- src/Definition/DefinitionFactoryInterface.php
This PR
See https://github.com/thephpleague/container/blob/master/src/Container.php#L68.
> Fix: DefinitionFactoryInterface needs to extend ImmutableContainerAwareInterface

- src/Definition/AbstractDefinition.php
- src/Definition/CallableDefinition.php
This PR
Follows https://github.com/thephpleague/container/pull/65#issuecomment-134236024.
> Fix: AbstractDefinition should implement DefinitionInterface

- src/Container.php
- src/ContainerAwareTrait.php
- src/Definition/ClassDefinitionInterface.php
- src/Definition/DefinitionInterface.php
- src/ImmutableContainerAwareTrait.php
- src/Inflector/Inflector.php
- src/ServiceProvider/ServiceProviderAggregateInterface.php
> Fix: Undefined class

- src/Argument/ArgumentResolverTrait.php
- src/ReflectionContainer.php
- tests/ReflectionContainerTest.php
> Fix: Add coverage for ReflectionContainer, fix bugs

- src/Container.php
- tests/ContainerTest.php
> Fix: Assert that container iterates stack

- src/ContainerInterface.php
> Fix: Docblock

- src/Argument/ArgumentResolverTrait.php
> Fix: Trait can't inherit docblock

- src/Container.php
- tests/ContainerTest.php
This PR
:person_with_pouting_face: Not sure if the removal was intended, but currently doesn't work as expected.
> Fix: Allow items to be shared

- auto-wiring.md
Previous link to `delegate`'s page was broken within the
`auto-wiring.md` file.
> Fix link to delegate

- src/Container.php
- tests/ContainerTest.php
This PR
Follows #72.
:person_with_pouting_face: Ha, I missed this one!
> Fix: Assert that has() returns true for shared definition

- src/Container.php
- tests/Asset/SharedServiceProviderFake.php
- tests/ContainerTest.php
This PR
Follows #72.
:information_desk_person: Came across this when updating a project to `league/container:^2.0.1` where I got tests, hehe.
> Fix: Allow to fetch shared service from service provider

- src/Container.php
- tests/ContainerTest.php
This PR
Fixes https://github.com/thephpleague/container/issues/78.
> Fix: Inject delegating container into delegated container

- getting-started.md
- Code samples where variable `$service` was used but not declared
> Fixed code samples

- src/Argument/ArgumentResolverTrait.php
- tests/Asset/FooWithScalarResolvedDependency.php
- tests/Definition/ClassDefinitionTest.php
In the case where a scalar parameter is set to null, Container assumes an unset value and replaces it with the $name argument. This PR enables storing RawArgument objects into the container and use the stored value upon resolving dependant's arguments.
Updated PR to match contribution guidelines.
> Allow resolving of scalar values from stored RawArgument objects

- src/ServiceProvider/AbstractServiceProvider.php
- src/ServiceProvider/ServiceProviderAggregate.php
- src/ServiceProvider/ServiceProviderInterface.php
- tests/Asset/SharedServiceProviderFake.php
- tests/ContainerTest.php
The existing ServiceProviderAggregate invariantly uses `get_class` to keep track of each provider to quickly and efficiently check to see if it has already been registered at some point in the past. This implementation prevents the use of the same Provider class to register services for multiple service providers.
For example, in instances where an application has a number of providers, all of which register services in a similar way, then a single simple service provider, such as [SimpleServiceProvider](https://github.com/Codegyre/Robo/blob/task-assembly/src/Container/SimpleServiceProvider.php) could potentially be used to handle all of them.  ([Example usage](https://github.com/Codegyre/Robo/blob/task-assembly/src/Task/File/loadTasks.php#L14)).
This technique works fine for the first …
> Add a 'signature' method to ServiceProviderInterface

- src/ServiceProvider/ServiceProviderAggregateInterface.php
This PR
Somewhat, but not really related to #96.
:information_desk_person: The parameter is called `$service` in the implementation, and as it is a string, it should probably the service identifier, rather than the actual provider.
> Fix: Rename parameter

- src/ReflectionContainer.php
- tests/ReflectionContainerTest.php
This commit fixes a compatibility issue between leauge/container and
league/route. With this fix it is possible to use "Action Controller" or
"Magic __invoke" able Controller with the ParamStrategy.
In fact it simply fixes callable classes in conjunction with the
ReflectionContainer. It should be fully backwards compatible as the
function itself relies on the 'callable' typehint for its first
parameter.
> Fixes ReflectionContainer::call for invokable objects.

- composer.json
This PR
💁 Because we can't tell yet whether `league/container` will be compatible with PHP 9000.
> Fix: Limit range of accepted PHP versions

- src/Container.php
- tests/ContainerTest.php
This change fixes the behavior of the Container::getFromThisContainer()
and Container::getFromDelegate() methods. Both of these methods return
either a value resolved from the container/delegate/provider or false.
While registering services that return a boolean false is allowed,
retrieving them caused a NotFoundException to bubble as the calling
method, Container::get() cannot differentiate from false literals
returned as a value from the container and false values returned by
the underlying methods failing to resolve an alias.
This change modifies the above methods to always return the resolved
value OR throw a NotFoundException which corrects the problematic
behavior of returning a value (false) as an indicator of an exception state
(method was asked for a thing and couldn't provide …
> Fix: Handle boolean values set on containers

- src/Container.php
- tests/ContainerTest.php
This fixes the issue where it was not able to register a non-shared definition when `defaultToShared` was enabled.
> Fix for issue #149

- src/Definition/Definition.php
- src/Definition/DefinitionInterface.php
- tests/Definition/DefinitionTest.php
Added a `getConcrete` and `setConcrete` method to the definition.
This fixes #151.
> Add getConcrete and setConcrete on the definition

- docs/3.x/definitions.md
I found two typos in the definitions.md
> Fix typos in definitions.md

- .gitattributes
This is to reduce package size when installing with `--prefer-dist` flag
> Add `/docs` to export ignore list

- src/ServiceProvider/ServiceProviderAggregate.php
- tests/ServiceProvider/ServiceProviderAggregateTest.php
When a ServiceProvider is added multiple times (either directly
or by other ServiceProviders), it should only be aggregated once.
This prevents iterating over the same ServiceProvider multiple times
when a service is provided by a provider farther down in the providers
stack, as well as executing the `boot()` method multiple times on any
BootableServiceProviders.
Fixes https://github.com/thephpleague/container/issues/157
> Fix issue where providers may be aggregated multiple times

- .travis.yml
- CONTRIBUTING.md
- README.md
- composer.json
- phpstan.neon
- src/Definition/Definition.php
- src/Inflector/Inflector.php
- src/Inflector/InflectorAggregate.php
- src/ReflectionContainer.php
Phpstan requires PHP 7.1 so in order to save some pain with getting Travis CI to run tests for PHP 7.0 I opted to just bump the minimum required version.
Some minor code changes were required to make phpstan happy:
* manually indicate that some callables are callable and not `[array, mixed]`
* the usual handling of  `array|false` that never happens in practice
> Add phpstan, bump minimum PHP version to 7.1

- README.md
The gh-pages branch no longer exists. This PR will fix the link to the documentation.
> Update link to the documentation

- src/Definition/Definition.php
Using the array keys also means faster isset() search calls than in_array(...) calls
> Allow adding the same tag once only
